### ISSUE TITLE
KLD adaptive sample size incompatible with most resampling methods

### ISSUE THREAD

**Issue by tbolin** [mrpt-ros-pkg/mrpt_navigation#114]
The mrpt_localization_node process dies upon initiation if resampling method 1, 2 or 3 (residual, stratified or systematic) is selected if adaptiveSampleSize is also enabled. 
The node dies with the message 

```
[mrpt_localization_node-10] process has died [pid 22358, exit code -6, cmd /opt/ros/kinetic/lib/mrpt_localization/mrpt_localization_node __name:=mrpt_localization_node __log:=/home/nvidia/.ros/log/e730a9e6-e108-11e9-b57a-00044ba56804/mrpt_localization_node-10.log].
log file: /home/nvidia/.ros/log/e730a9e6-e108-11e9-b57a-00044ba56804/mrpt_localization_node-10*.log
```
The log file mentioned in the error message do not exist. I'll attach the master log file from one run: [master.log](https://github.com/mrpt-ros-pkg/mrpt_navigation/files/3662073/master.log)

Steps to replicate:
1. Make a copy of `pf-localization.ini` from the tutorial.
2. Change `resamplingMethod` on line 41 from 0 to 1, 2 or three.
3. Start a localization node with the new .ini file.

**Comment by jlblancoc** [comment]
Hi, and sorry for the late reply. 
Two points: 
1) The crash is due to an exception, but it's hard to see the output to cerr with ros... You could enable output="screen" in the roslaunch, if it's not already enabled, or [use gdb](http://wiki.ros.org/roslaunch/Tutorials/Roslaunch%20Nodes%20in%20Valgrind%20or%20GDB) within the roslaunch, then show the a backtrace at the exception to 100% identify the problem.

2) At the theoretical level: using a dynamic sample size requires, as far as I could ever devise, using the multinomial method, that's why using any other method raises an exception. In other words: that's the expected behavior ;-)
