### ISSUE TITLE
Really makes sense to stop updating the localization particle filter when not moving?

### ISSUE THREAD

**Issue by corot** [mrpt-ros-pkg/mrpt_navigation#53]
I added the change on c6526eaa84f58356a4cf538a892afbfa77bf0e55, but now I have noticed that it's way more elegant to play instead with gaussian_alpha_phi and gaussian_alpha_xy parameters. If set to zero, filter doesn't change when robot is stopped.

I reverted c6526eaa84f58356a4cf538a892afbfa77bf0e55 in my own repo, but I prefer to ask before PRequesting the change. What do you think? Should we add instead a dynamically re-configurable parameter so users can decide?

**Comment by jlblancoc** [comment]
good point! Yes, the modification of odometry noise params is "more elegant", but requires the user to change them. Do the PR please to rever the changes. Only if you have time and it's easy (I think it should be...), add the new "bool" checkbox to let users stop updating the PF if the robot is stopped. IMO, the default should be "don't stop running the PF when stopped", for consistency with the default behavior in MRPT, and because that may be what most people expect...

Thanks!
